GTCEuStartupEvents.registry("gtceu:material_icon_set", event => {
	event.create("aquatic").parent(GTMaterialIconSet.SHINY)
})

GTCEuStartupEvents.registry("gtceu:material", event => {
	const $OreProperty = Java.loadClass("com.gregtechceu.gtceu.api.data.chemical.material.properties.OreProperty");
	const $IngotProperty = Java.loadClass("com.gregtechceu.gtceu.api.data.chemical.material.properties.IngotProperty");
	const $BlastProperty = Java.loadClass("com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty");
	GTMaterials.get("andesite_alloy").addFlags(GTMaterialFlags.GENERATE_GEAR);
	GTMaterials.Iron.addFlags(GTMaterialFlags.GENERATE_FINE_WIRE);
	GTMaterials.Zinc.setProperty(PropertyKey.ORE, new $OreProperty());
	GTMaterials.Ytterbium.setProperty(PropertyKey.INGOT, new $IngotProperty());
	GTMaterials.Ytterbium.setProperty(PropertyKey.BLAST, new $BlastProperty(7200, "higher", GTValues.VA[GTValues.IV], 900, -1, -1));
	
	//primarine line chemicals
	event.create("phosgene")
		.liquid()
		.components( "carbon", "2x chlorine", "oxygen")
		.color(0x0a7647)
	event.create("anilene")
		.liquid()
		.components( "6x carbon", "7x hydrogen", "nitrogen")
		.color(0x346811)
	event.create("hydrazine")
		.liquid()
		.components( "4x hydrogen", "2x nitrogen")
		.color(0x5360c0)
	event.create("diethyl_carbonate")
		.liquid()
		.components( "5x carbon", "10x hydrogen", "3x oxygen")
		.color(0xc2ffe4)
	event.create("phenyl_isocyanate")
		.liquid()
		.components( "7x carbon", "5x hydrogen", "nitrogen", "oxygen")
		.color(0x011208)
	event.create("benzvalene")
		.liquid()
		.components("benzene")
		.color(0x000a0a)
	event.create("schembl5306506")
		.liquid()
		.components("8x carbon", "5x hydrogen", "nitrogen", "2x oxygen")
		.color(0xEC4232)
	event.create("ptad")
		.dust()
		.components("schembl5306506", "2x nitrogen")
		.color(0xEC4232)
	event.create("ptad_benzvalene")
		.dust()
		.components("benzvalene", "ptad")
		.color(0xEC4232)
	event.create("prismane")
		.dust()
		.components("benzene")
		.color(0x004030)
	//UHV materials
	event.create("prismarine")
		.gem()
		.components("4x prismane", "2x lapis", "8x ytterbium")
		.color(0xA4D1C2).secondaryColor(0x539882).iconSet("aquatic")
	event.create("activated_prismarine")
		.ingot()
		.components("1x prismarine", "trinium_sulfide")
		.color(0x008070).iconSet("aquatic")
		.flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_LONG_ROD, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_ROTOR)
		.fluidPipeProperties(45000, 45000, false)
		.blastTemp(9635, "highest", GTValues.VA[GTValues.UV])
	event.create("tritanium_fluoride")
		.ingot()
		.components("1x tritanium", "fluorine")
		.color(0x601000).iconSet(GTMaterialIconSet.SHINY)
	event.create("tritanium_hexafluoride")
		.ingot()
		.components("1x tritanium", "6x fluorine")
		.color(0x606000).iconSet(GTMaterialIconSet.SHINY)
	event.create("awakened_lapis")
		.ingot()
		.components("1x lapis", "1x tritanium_hexafluoride")
		.color(0x0000FF).iconSet("lapidary")
		.flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_LONG_ROD, GTMaterialFlags.GENERATE_BOLT_SCREW)
		.blastTemp(10531, "highest", GTValues.VA[GTValues.UV])
	//charcoals, cokes
	event.create("cactus_charcoal")
		.gem(0, 800)
		.components("carbon")
		.color(0x00AA00).iconSet(GTMaterialIconSet.LIGNITE)
	event.create("cactus_coke")
		.gem(0, 1600)
		.components("carbon")
		.color(0x00FF00).iconSet(GTMaterialIconSet.LIGNITE)
	event.create("sugar_charcoal")
		.gem(0, 800)
		.components("carbon")
		.color(0xAAAAAA).iconSet(GTMaterialIconSet.LIGNITE)
	event.create("sugar_coke")
		.gem(0, 1600)
		.components("carbon")
		.color(0xFFFFFF).iconSet(GTMaterialIconSet.LIGNITE)
	event.create("kelp_coke")
		.dust(0, 8000)
		.components("carbon")
		.color(0x444444).iconSet(GTMaterialIconSet.LIGNITE)
	//mod integration materials
	event.create("charged_certus_quartz")
		.gem()
		.color(0x9fd5e8)
		.iconSet(GTMaterialIconSet.CERTUS)
		.flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
		.components("certus_quartz")
	event.create("fluix")
		.gem()
		.color(0x7f5bb3)
		.iconSet(GTMaterialIconSet.CERTUS)
		.flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.CRYSTALLIZABLE)
		.components("charged_certus_quartz", "redstone", "nether_quartz")
	event.create("asurine")
		.dust()
		.components("9x zinc", "saltpeter")
		.color(0x6b98b4)
		.secondaryColor(0x323b55).iconSet(GTMaterialIconSet.DIAMOND)
		.flags(GTMaterialFlags.DECOMPOSITION_BY_CENTRIFUGING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.FORCE_GENERATE_BLOCK)
	event.create("crimsite")
		.dust()
		.components("9x hematite", "redstone")
		.color(0xb26555)
		.secondaryColor(0x40272f).iconSet(GTMaterialIconSet.FLINT)
		.flags(GTMaterialFlags.DECOMPOSITION_BY_CENTRIFUGING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.FORCE_GENERATE_BLOCK)
	event.create("ochrum")
		.dust()
		.components("9x gold", "quartzite")
		.color(0xb89b5f)
		.secondaryColor(0x743c34).iconSet(GTMaterialIconSet.LIGNITE)
		.flags(GTMaterialFlags.DECOMPOSITION_BY_CENTRIFUGING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.FORCE_GENERATE_BLOCK)
	event.create("veridium")
		.dust()
		.components("9x malachite", "clay")
		.color(0x50977d)
		.secondaryColor(0x133b3d).iconSet(GTMaterialIconSet.LIGNITE)
		.flags(GTMaterialFlags.DECOMPOSITION_BY_CENTRIFUGING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.FORCE_GENERATE_BLOCK)
})
GTCEuStartupEvents.materialModification(event => {
	const $AEItems = Java.loadClass("appeng.core.definitions.AEItems");
	const $AEBlocks = Java.loadClass("appeng.core.definitions.AEBlocks");
	const $CreatePaletteBlocks = Java.loadClass("com.simibubi.create.content.decoration.palettes.AllPaletteStoneTypes");
	
	const $PBeeItems = Java.loadClass("cy.jdkdigital.productivebees.init.ModItems");
	const $PBeeBlocks = Java.loadClass("cy.jdkdigital.productivebees.init.ModBlocks");
	
	GTMaterials.Zinc.setMaterialARGB(0xd6ffdc)
	GTMaterials.Zinc.setMaterialSecondaryARGB(0x31544e)
	//GTMaterials.Naquadria.cableProperties(GTValues.VA[GTValues.UEV], 1, 16)
	//TagPrefix.gem.setIgnored(GTMaterialRegistry.getMaterial("rose_quartz"), $CreateItems.ROSE_QUARTZ)
	TagPrefix.block.modifyMaterialAmount(GTMaterialRegistry.getMaterial("rose_quartz"), 4)
	
	TagPrefix.block.setIgnored(GTMaterialRegistry.getMaterial("asurine"), $CreatePaletteBlocks.ASURINE)
	TagPrefix.block.setIgnored(GTMaterialRegistry.getMaterial("crimsite"), $CreatePaletteBlocks.CRIMSITE)
	TagPrefix.block.setIgnored(GTMaterialRegistry.getMaterial("ochrum"), $CreatePaletteBlocks.OCHRUM)
	TagPrefix.block.setIgnored(GTMaterialRegistry.getMaterial("veridium"), $CreatePaletteBlocks.VERIDIUM)
	
	TagPrefix.gem.setIgnored(GTMaterialRegistry.getMaterial("prismarine"), Ingredient.of("minecraft:prismarine_crystals"))
	TagPrefix.dust.setIgnored(GTMaterialRegistry.getMaterial("prismarine"), Ingredient.of("minecraft:prismarine_shard"))
	
	TagPrefix.gem.setIgnored(GTMaterialRegistry.getMaterial("certus_quartz"), $AEItems.CERTUS_QUARTZ_CRYSTAL)
	TagPrefix.dust.setIgnored(GTMaterialRegistry.getMaterial("certus_quartz"), $AEItems.CERTUS_QUARTZ_DUST)
	TagPrefix.block.setIgnored(GTMaterialRegistry.getMaterial("certus_quartz"), $AEBlocks.QUARTZ_BLOCK)
	
	TagPrefix.gem.setIgnored(GTMaterialRegistry.getMaterial("charged_certus_quartz"), $AEItems.CERTUS_QUARTZ_CRYSTAL_CHARGED)
	TagPrefix.block.modifyMaterialAmount(GTMaterialRegistry.getMaterial("charged_certus_quartz"), 4)
	
	TagPrefix.dust.setIgnored(GTMaterialRegistry.getMaterial("fluix"), $AEItems.FLUIX_DUST)
	TagPrefix.gem.setIgnored(GTMaterialRegistry.getMaterial("fluix"), $AEItems.FLUIX_CRYSTAL)
	TagPrefix.block.setIgnored(GTMaterialRegistry.getMaterial("fluix"), $AEBlocks.FLUIX_BLOCK)
	TagPrefix.block.modifyMaterialAmount(GTMaterialRegistry.getMaterial("fluix"), 4)
	
	TagPrefix.dust.setIgnored(GTMaterialRegistry.getMaterial("ender_pearl"), $AEItems.ENDER_DUST)
	
	TagPrefix.ingot.setIgnored(GTMaterialRegistry.getMaterial("wax"), $PBeeItems.WAX)
	TagPrefix.block.setIgnored(GTMaterialRegistry.getMaterial("wax"), $PBeeBlocks.WAX_BLOCK)
})
GTCEuStartupEvents.craftingComponents(event => {
	event.setMaterialEntry(GTCraftingComponents.PLATE, GTValues.UEV, new MaterialEntry("plate", "gtceu:activated_prismarine"))
	event.setMaterialEntry(GTCraftingComponents.ROTOR, GTValues.UEV, new MaterialEntry("rotor", "gtceu:activated_prismarine"))
	event.setMaterialEntry(GTCraftingComponents.FRAME, GTValues.UEV, new MaterialEntry("frame", "gtceu:activated_prismarine"))
	event.setMaterialEntry(GTCraftingComponents.PIPE_REACTOR, GTValues.UEV, new MaterialEntry("pipeHugeFluid", "gtceu:polybenzimidazole"))
	event.setMaterialEntry(GTCraftingComponentsSENSOR_EMITTER_GEM, GTValues.UEV, new MaterialEntry("gemFlawless", "gtceu:prismarine"))
	
})
/*StartupEvents.registry("block", event => {
	event.create("lapis_coil_block", "gtceu:coil")
		.temperature(13200)
		.level(16)
		.energyDiscount(16)
		.tier(10)
		.coilMaterial(() => GTMaterials.get("infinity"))
		.texture("gtceu:block/casings/coils/")
		.hardness(5)
		.requiresTool(true)
		.material("metal")
})*/
